### PR TITLE
Add support for average center marker clustering

### PR DESCRIPTION
**Pull request by bentleyo**
Controls whether the position of a cluster marker should be the average
position of all markers in the cluster (defaults to the position of the
first marker in the cluster).

This is a useful feature of the `markerclusterer`.

### CODE REVIEW

**Comment by diegoazh** [comment]
This change looks like for me, any one have comments?

**Review by diegoazh — CHANGES_REQUESTED** [review]
Please discard the changes on `dist/` folder in order to merge this PR

**Comment by bentleyo** [comment]
@diegoazh I have amended the commit as requested. What is the process of having this built in the release?

**Comment by diegoazh** [comment]
Thank you for you contribution @bentleyo, I will merge this changes but the new release depends on @xkjyeah, I hope that him release a new version every one o two weeks if the main branch has changes.

**Comment by diegoazh** [comment]
Congratulations @bentleyo you PR has been landed! 🎉🎊

**Comment by diegoazh** [comment]
@xkjyeah when you think that a new release can be ready?

**Pull request merged**
