### PR TITLE
add "async" and "defer" as options on the load manager

### PR DESCRIPTION
**Pull request by KiVeR**

### CODE REVIEW

**Comment by xkjyeah** [comment]
So you want to make async / defer optional? Why?

**Comment by diegoazh** [comment]
Please resolve this conflicts:
```
dist/components/autocompleteImpl.js
dist/components/mapImpl.js
dist/manager.js
dist/vue-google-maps-stubbed.js
dist/vue-google-maps.js
src/manager.js
```

**Review by diegoazh — CHANGES_REQUESTED** [review]
@KiVeR please remove the changes on `dist/` folder and resolve the conflicts after that looks like for me to be merged.
If any one have comments, please leave a comment.
What do you think @xkjyeah?

**Comment by diegoazh** [comment]
I think that should be closed for inactivity

**Comment by diegoazh** [comment]
Closed for inactivity 😔

**Pull request closed without merging**
