### PR TITLE
Optimize: Reduce overhead generated by unused events

### PR DESCRIPTION
**Pull request by armano2**
Reduce overhead generated by unused events

### CODE REVIEW

**Comment by xkjyeah** [comment]
Thanks for the contribution!

**Comment by xkjyeah** [comment]
Do you think you could make the change for propsBinder too? Then I'll merge it in and publish the changes.

**Comment by armano2** [comment]
Ok

**Comment by armano2** [comment]
From what i seen you updated code, and i changed this PR

**Pull request closed without merging**
