### PR TITLE
Adding probot to close issues that no have a response after a more in…

### PR DESCRIPTION
**Pull request by diegoazh**
To close issues automatically when author not responds to more information request.

### CODE REVIEW

**Comment by diegoazh** [comment]
@xkjyeah can you [configure the github app](https://github.com/apps/no-response)? My soruce is [https://github.com/probot/no-response](https://github.com/probot/no-response)

**Comment by diegoazh** [comment]
I'm not sure if 30 days is to much, if you want I change it to 14 days as default @xkjyeah.

**Comment by AllanOcelot** [comment]
I agree with 14 days, I'm looking to start contributing and helping out with issues, but the amount of abandoned ones is crazy, great PR :)

**Comment by diegoazh** [comment]
@xkjyeah are you in agreement with this change, if yes please can you active probot in this project?, if not please let me know in order to close this PR.
Thank you.

**Pull request closed without merging**
