### PR TITLE
Fixed dependencies + Linting; Added Eventbinder to markerCluster; CustomData on marker

### PR DESCRIPTION
**Pull request by PaulHindenberg**
# Fixed dependencies + Linting
- Due to the nature of npm v3 peer-dependencies aren't installed by default anymore. So the marker-cluster-plus was moved to dependencies.
- babel-runtime, stage-2 and plugin-transform-runtime were also added to the dependencies. Without these installed you will get an error. 
- The npm script `test` didn't work due to typo.
- The npm script `eslint` was also broken due to the missing `eslint-plugin-html` dependency 

# Added Eventbinder to markerCluster
- added events to markerClusters through props via eventbinder

# CustomData on marker
- added customData to marker via prop as Object with the use of @krues8dr [gist](https://gist.github.com/krues8dr/3040600)

### CODE REVIEW

**Comment by xkjyeah** [comment]
Hi Paul,

Thanks for the work you put in. I'm going to incorporate most of them into the next version, but I have doubts about the CustomData. What's the use case for it? If you are using it with Vue, how is this any better than declaring a new component:

```html
<template>
<gmap-marker></gmap-marker>
</template>
<script>
export default {
    props: ['customProp']
}
</script>
```

I am hesitant to unnecessarily extend this library with features beyond the Google Maps API. However, I'm open to having `contrib` components having extra bells and whistles.

**Comment by xkjyeah** [comment]
Ooops the merge was a mistake. I had removed the Custom Data parts so it's not a complete merge. Sorry!

**Comment by bastilimbach** [comment]
Hi @xkjyeah, thanks for the quick response. I worked with @PaulHindenberg on this PR.
We included the custom data part for following use case:

Usually, if you use the normal google maps api without vue, you create the markers like this:
```javascript
var marker = new google.maps.Marker({
    position: myLatLng,
    map: map,
    title: 'Hello World!'
  });
```
Your vue implementation does this by creating a marker with a javascript object `new google.maps.Marker(options)` but this doesn't allow us to apply custom data to the marker. For example, we create our markers like so:
```javascript
var marker = new google.maps.Marker({
    position: myLatLng,
    map: map,
    title: 'Hello World!',
    record: {
        temp: 52.49266,
        id: 883
        location: {...}
   }
  });
```
This does give us the advantage that we can use this data later on. In our use case we click on a specific marker, get the marker object and get the record `temp` of this exact marker:
```javascript
marker.addListener('click', function (marker) {
    console.log(marker.record.temp)
})
```

**Comment by zashton** [comment]
@bastilimbach 
You could use the created marker object and do

````javascript
marker.record = {
        temp: 52.49266,
        id: 883
        location: {...}
   }
````

**Comment by krusynth** [comment]
FWIW, the magic in my gist was the closure wrapping around the marker creation, which used variable hoisting to allow access to the custom data inside of the onclick callback for the marker, since (at least then) the Google Maps API did not give you access to the original marker inside of the `onclick` event callback.  The getter/setter methods are just decoration.

**Comment by xkjyeah** [comment]
Yup, except with Vue-google-maps it's not necessary any more.

You can get access to all the data you need since Vue's managing it:
```html
<gmap-marker v-for="item in items"
    @click="doSomethingWith($event, item.customData1, item.customData2, ...)" />
```

**Comment by bastilimbach** [comment]
I should have been more explicit about our use case, sorry. With the click event listener on the markers, this isn't a problem. We implemented it as @xkjyeah did it. The problem is, that we need the custom marker data at the click event triggered by the marker cluster.

The process looks like the following:

1. markerCluster clicked
2. the click method gives back the `Cluster` object
3. we loop through the object and search for the `Cluster.markerClusterer_.clusters_.markers_` array
4. then we get the data from each marker (with custom data)

screenshot

**Comment by xkjyeah** [comment]
I see...

Okay, fair enough. Since this library supports Marker Clusterer it should
also support custom data in order to access data from the clusterer.

On Fri, Mar 17, 2017 at 4:13 PM, Sebastian Limbach <notifications@github.com

**Comment by xkjyeah** [comment]
Let's discuss this in a separate issue https://github.com/xkjyeah/vue-google-maps/issues/72

**Pull request merged**
