### PR TITLE
Added Streetview Markers

### PR DESCRIPTION
**Pull request by trueChazza**
- Created example page
- Created element mixin
- Created and registered component

### CODE REVIEW

**Comment by diegoazh** [comment]
Please resolve the following conflicts doing a pull of master on your branch:
```text
src/main.js
```
After that, please resolve the build errors:
[https://travis-ci.org/xkjyeah/vue-google-maps/builds/368356332?utm_source=github_status&utm_medium=notification](https://travis-ci.org/xkjyeah/vue-google-maps/builds/368356332?utm_source=github_status&utm_medium=notification)
Regards.

**Comment by diegoazh** [comment]
@trueChazza can you resolve the conflicts and fix this errors on the build? after that the change looks very good for me.
If any one have comments on this approach please let us know.

```console
    ERROR in ./src/components/streetViewElementMixin.js
    Module not found: Error: Can't resolve '../utils/deferredReady' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewElementMixin.js 7:21-54
     @ ./src/main.js
     @ multi ./src/main.js
    
    ERROR in ./src/components/streetViewMarker.js
    Module not found: Error: Can't resolve '../utils/eventsBinder.js' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewMarker.js 11:20-55
     @ ./src/main.js
     @ multi ./src/main.js
    
    ERROR in ./src/components/streetViewMarker.js
    Module not found: Error: Can't resolve '../utils/getPropsValuesMixin.js' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewMarker.js 19:27-69
     @ ./src/main.js
     @ multi ./src/main.js
    
    ERROR in ./src/components/streetViewMarker.js
    Module not found: Error: Can't resolve '../utils/propsBinder.js' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewMarker.js 15:19-53
     @ ./src/main.js
     @ multi ./src/main.js
Child
    Hash: 15ce1506a0ac843cf027
    Time: 11003ms
    Built at: 2018-4-18 21:19:49
     1 asset
    Entrypoint main = vue-google-maps-stubbed.js
    
    ERROR in ./src/components/streetViewElementMixin.js
    Module not found: Error: Can't resolve '../utils/deferredReady' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewElementMixin.js 7:21-54
     @ ./src/main.js
     @ multi ./src/main.js
    
    ERROR in ./src/components/streetViewMarker.js
    Module not found: Error: Can't resolve '../utils/eventsBinder.js' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewMarker.js 11:20-55
     @ ./src/main.js
     @ multi ./src/main.js
    
    ERROR in ./src/components/streetViewMarker.js
    Module not found: Error: Can't resolve '../utils/getPropsValuesMixin.js' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewMarker.js 19:27-69
     @ ./src/main.js
     @ multi ./src/main.js
    
    ERROR in ./src/components/streetViewMarker.js
    Module not found: Error: Can't resolve '../utils/propsBinder.js' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewMarker.js 15:19-53
     @ ./src/main.js
     @ multi ./src/main.js
```

**Review by diegoazh — CHANGES_REQUESTED** [review]
@trueChazza can you resolve the conflicts and fix this errors on the build? after that the change looks very good for me.
If any one have comments on this approach please let us know.

```console
    ERROR in ./src/components/streetViewElementMixin.js
    Module not found: Error: Can't resolve '../utils/deferredReady' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewElementMixin.js 7:21-54
     @ ./src/main.js
     @ multi ./src/main.js
    
    ERROR in ./src/components/streetViewMarker.js
    Module not found: Error: Can't resolve '../utils/eventsBinder.js' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewMarker.js 11:20-55
     @ ./src/main.js
     @ multi ./src/main.js
    
    ERROR in ./src/components/streetViewMarker.js
    Module not found: Error: Can't resolve '../utils/getPropsValuesMixin.js' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewMarker.js 19:27-69
     @ ./src/main.js
     @ multi ./src/main.js
    
    ERROR in ./src/components/streetViewMarker.js
    Module not found: Error: Can't resolve '../utils/propsBinder.js' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewMarker.js 15:19-53
     @ ./src/main.js
     @ multi ./src/main.js
Child
    Hash: 15ce1506a0ac843cf027
    Time: 11003ms
    Built at: 2018-4-18 21:19:49
     1 asset
    Entrypoint main = vue-google-maps-stubbed.js
    
    ERROR in ./src/components/streetViewElementMixin.js
    Module not found: Error: Can't resolve '../utils/deferredReady' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewElementMixin.js 7:21-54
     @ ./src/main.js
     @ multi ./src/main.js
    
    ERROR in ./src/components/streetViewMarker.js
    Module not found: Error: Can't resolve '../utils/eventsBinder.js' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewMarker.js 11:20-55
     @ ./src/main.js
     @ multi ./src/main.js
    
    ERROR in ./src/components/streetViewMarker.js
    Module not found: Error: Can't resolve '../utils/getPropsValuesMixin.js' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewMarker.js 19:27-69
     @ ./src/main.js
     @ multi ./src/main.js
    
    ERROR in ./src/components/streetViewMarker.js
    Module not found: Error: Can't resolve '../utils/propsBinder.js' in '/home/travis/build/xkjyeah/vue-google-maps/src/components'
     @ ./src/components/streetViewMarker.js 15:19-53
     @ ./src/main.js
     @ multi ./src/main.js
```

**Comment by trueChazza** [comment]
@diegoazh sure I’ll resolve conflicts.

**Comment by diegoazh** [comment]
I think that this PR should be closed for inactivity

**Pull request closed without merging**
