### PR TITLE
Add cluster min size option

### PR DESCRIPTION
**Pull request by mercs600**
Added missing prop

### CODE REVIEW

**Review by xkjyeah — CHANGES_REQUESTED** [review]
Hi, do you mind deleting the files in dist before committing again? This will keep the source code changes cleaner. I will regenerate the dist files when publishing

**Comment by xkjyeah** [comment]
Sorry, I mean reverting the files in dist to their original values, e.g. `git checkout -f HEAD~1 dist`

**Comment by mercs600** [comment]
@xkjyeah I fixed it

**Comment by seblucas** [comment]
Is there a problem remaining blocking this PR ?

**Review by xkjyeah — APPROVED** [review]

**Pull request merged**
