### PR TITLE
Update README with Style Addition

### PR DESCRIPTION
**Pull request by sdzharkov**
I basically tried to copy and paste the extended component provided above, but the map would not appear until I defined the style parameters. I wasted a good amount of time trying to render the map and this issue could totally be avoided for those who prefer to use components.

### CODE REVIEW

**Comment by xkjyeah** [comment]
Doesn't it work when you add the style directly to the gmap-map?

**Comment by sdzharkov** [comment]
Doesn't work for me, I tried 
`:style="{ width: '500px', height: '500px'}"`, `:style="{ width: 500+'px', height: 500+'px'}"`, `      :style="{ width: 500px, height: 500px}"` to the <gmap-marker component or the <gmap-map component but the map was still not visible. 

I don't know if this matters but I'm also writing this within a .vue file. Adding the <style> tags was the way I got it to work.

**Comment by xkjyeah** [comment]
Have you upgraded to the latest version?

npm install vue2-google-maps@latest

Previously correct sizing of the maps required a wrapper div; which I found
was rather silly; but I had changed that only in the last couple of days.

In any case, thanks for making this PR!

**Comment by sdzharkov** [comment]
Awesome thanks!

**Pull request closed without merging**
