### PR TITLE
Added Options property to Marker

### PR DESCRIPTION
**Pull request by awshrubsall**
#192

### CODE REVIEW

**Comment by xkjyeah** [comment]
Hey thanks for this commit. I didn't realize the option prop was missing!

Could you make the change in src/ instead of dist/? I'll rebuild the dist part when publishing the new version.

**Comment by awshrubsall** [comment]
Apologies, I am new to github so modified the wrong file, how to I change it, just make another pull request on the correct file?

**Comment by xkjyeah** [comment]
tl;dr `git commit --amend` and then `git push -f`

**Comment by awshrubsall** [comment]
Alright, it's in src/ now.

**Review by xkjyeah — APPROVED** [review]

**Pull request merged**
