### PR TITLE
Update polyline.js

### PR DESCRIPTION
**Pull request by varna**
Adding `immediate: true` to watcher.
Fixes not working `path_changed` event on Polyline #411

### CODE REVIEW

**Comment by varna** [comment]
I figured that this package is not very active, so I made a "release". It's in the same branch, not sure if that's OK. But I can use it with NPM now.
A problem came out, it seems that position_changed event on marker is firing infinitely.

**Comment by xkjyeah** [comment]
Hi sorry for the delay in merging.

One comment: could you remove the extra files in `dist/`? They are not part of the source code changes.

**Comment by varna** [comment]
I'm duplicating this pull request without that "mistake".

**Comment by varna** [comment]
Sorry @xkjyeah wanted to avoid rebasing that branch, did new PR https://github.com/xkjyeah/vue-google-maps/pull/438

**Pull request closed without merging**
